apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-staging
spec:
  destination:
    namespace: policies-staging
    server: https://kubernetes.default.svc
  source:
    path: policies/staging
    repoURL: https://github.com/TykTechnologies/tyk-operator-demo
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true